# ชนิดข้อมูลเชิงประกอบ (Composite data types)

มีอยู่ 3 ตัว

1.   ลิสต์​ (lists)
2.   ทัพเพิล (Tuples)
3.   ดิกชันนารี (Dictionary)
4.   เซต (Set)

ลิสต์ (lists) มีความสามารถในการเก็บข้อมูลชนิดต่่างชนิดกันได้  คล้ายกับอะเรย์ (Array) แต่อะเรย์มีความสามารถในการเก็บข้อมูลชนิดเดียวกันเท่านั้น มีตำแหน่งลำดับในการเข้าถึงเหมือนกับข้อมูลชนิด String และ Array

ยกตัวอย่างเช่น

## ข้อมูล List

In [ ]:
#String เก็บข้อความเท่านั้น
x = "H123"

#List เก้บข้อมูลต่างชนิดไว้ได้
y = ['H',1,2,3]

#print(x[1]+x[2])
#print(y[1]+y[2])

#รายการ ประวัติพี่ปริ้น
fistname = 'Nakrit'
lastname = 'Aree'
id = '36390'
age = 13
tel = '0642108180'

#รายการ ประวัติน้องเปา
fistname = 'Nakorn'
lastname = 'Aree'
id = '37374'
age = 11
tel = '0800531035'

# ข้อมูลในลิสต์ คือ ชื่อ, นามสกุล, รหัส, อายุ, เบอร์โทร
pupprint = ['Nakrit','Aree','36390',13,'0642108180']
puppao = ['Nakorn','Aree','37374',11,'0800531035']

print('ชื่อ',pupprint[0],pupprint[1])
print('รหัส',pupprint[2])
print('อายุ',pupprint[3])
print('เบอร์โทร',pupprint[4])

ชื่อ Nakrit Aree
รหัส 36390
อายุ 13
เบอร์โทร 0642108180

In [ ]:
#สามารถเปรียบเทียบค่าใน List ได้ เช่น
x = [6,6,6,6]
y = [1,1,1,1]
#.   t,f,t,t = And คือ ค่าที่เปรียบเทียบใน List ต้องเป็นจริงทุกกรณีเท่านั้น
print(x < y)

False

In [ ]:
# ข้อมูลในลิสต์ คือ ชื่อ, นามสกุล, รหัส, อายุ, เบอร์โทร
pupprint = ['Nakrit','Aree','36390',13,'0642108180']
puppao = ['Nakorn','Aree','37374',11,'0800531035']

print(pupprint[0:3])

x = pupprint[0:3]
x[0]
x[4]

['Nakrit', 'Aree', '36390']

IndexError: ignored

## ข้อมูล ทัพเพิล (Tuples)

มีลักษณะโครงสร้างคล้าย List เก็บข้อมูลต่างชนิดกันได้เหมือนกัน แต่ เก็บข้อมูลที่เป็นค่าคงที่ และไม่เปลี่ยน ไม่สามารถเพิ่มหรือลบได้โดยตรง การเข้าถึงข้อมูลทำได้เหมือน List แต่จะอยู่ในเครื่องหมาย ( )

In [ ]:
pupprint = ['Nakrit','Aree','36390',13,'0642108180'] #list
x = ('Nakrit','Aree','36390',13,'0642108180') #tuple

print(pupprint[0])
print(x[0])

#List สามารถเปลี่ยนค่าได้
pupprint[4] = 15
print(pupprint[4])
print(len(pupprint))

#Tuple ไม่สามารถเปลี่ยนค่าได้
x[4] = 15
print(x[4])

Nakrit
Nakrit
15
5

TypeError: ignored

## ชนิดข้อมูล ดิกชันนารี (Dictionary)

คล้ายกับ List เก็บข้อมูลต่างชนิดกันได้ เก็บได้หลายค่า แต่สิ่งที่แตกต่างกัน คือ จะมีการเก็บข้อมูลเป็นคู่ คือมี Key กับ Value

ที่สัมพันธ์กันเสมอ และใช้สัญลัก { } ในการเก็บข้อมูลในนั้น

In [ ]:
list_ = ['Nakrit','Aree','36390',13,'0642108180'] #list
tuple_ = ('Nakrit','Aree','36390',13,'0642108180') #tuple

print(list_[0])

#firstname = 'Nakrit'
dictionary = {'firstname':'Nakrit','lastname':'Aree','id':'36390','age':13,'tel':'0642108180'} #dictionary
print(dictionary['firstname'], dictionary['lastname'])

Nakrit
Nakrit Aree

## ชนิดข้อมูล เซต (Set)

คล้ายกับ List แต่จะใช้สัญลักษณ์ {x1,x2,x3}

ในการประกาศแบบเซต จะใช้เป็น

x = set([1,2,3,4,5])

In [ ]:
# การใช้เซต
# 1.มันจะตัดข้อมูลซ้ำออกให้อัตโนมัติ
# 2.เมื่อประกาศเซต ต้องระวังตำแหน่งที่มันสร้างให้ใหม่

setA = set(['Banana','Orange','Mango'])
setB = set(['Banana','Orange','Mango','Apple','Durian'])

print('setA: ',setA)
print('setB: ',setB)

setA:  {'Banana', 'Mango', 'Orange'}
setB:  {'Apple', 'Orange', 'Banana', 'Durian', 'Mango'}

In [ ]:
# loop ข้อมูลใน set ออกมา
setA = set(['Banana','Orange','Mango'])
setB = set(['Banana','Orange','Mango','Apple','Durian'])

#ดึงข้อมูลมาใช้
listdat = []
for id in setA:
    listdat.append(id)

print(listdat)
print(listdat[0])

['Banana', 'Mango', 'Orange']
Banana

In [ ]:
# ฟังชันดำเนินการในเซ็ต
setA = set(['Banana','Orange','Mango'])
setB = set(['Banana','Orange','Mango','Apple','Durian'])

# add() เพิ่มได้ทีละ 1 ตัว
setA.add('Grape')
setA.add('Papaya')
setA.add('Apple')
setA

# update() จะอัพเดทข้อมูลที่เป็นชุด เพิ่มเข้าไปรวมกับของเก่า
setA.update(['Mango','Apple','Durian'])
setA

# pop()
x = setA.pop()
x

setA

# romove ใส่ชื่อตรงๆ ที่ต้องการลบ ไม่ใช่ตำแหน่ง
setA.remove('Banana')
setA

# clear() คือ ลบเซตออกทั้งหมด
setA.clear()
setA

set()

In [ ]:
# operator การดำเนินการในเซ็ต
setA = set(['Banana','Orange','Mango','Apple'])
setB = set(['Banana','Orange','Mango','Apple','Durian'])

# Intersection คือ การเลือกข้อมูลที่เหมือนfc                                                                    vfกันทั้ง 2 เซต มาจัดกลุ่มใหม่
setA & setB

# Union คือ การรวมข้อมูลทุกอย่างที่มีอยู่ในเซ็ต A และ B โดยไม่เอาข้อมูลซ้ำเข้ามารวมด้วย
setA | setB

# Complement (Diff) คือ การเอาข้อมูลที่ไม่เหมือนกัน ที่อยู่ในเซตซ้ายมือเท่านั้น
setA - setB

# Symetric Diff คือ การเลือกข้อมูลที่ทั้ง A และ B ไม่มีเหมือนกัน
setA ^ setB

{'Durian'}

## Loop การวนซ้ำ

1. for loop

2. while loop


**คำสั่ง for loop**

for ตัวแปร in string,list,tuple:

 คำสั่ง

In [ ]:
#print('Hello '*5)

#print('1','2','3','4','5')

#for loop.  range(start,จำนวน n-1) คือ เลข 5 จะเริ่มตั้งแต่ 0,1,2,3,4
#forcing int(), float(), str() x.append(i)

#for i in range(1,101): #บวก 1 เพราะตำแหน่งเริ่มที่ 0
    #print(i)

#for ใน string
#for get in 'Hello World':
#    print(get)

#for ใน list
#for y in ['Nakrit','Aree','36390',13,'0642108180']:
#    print(y)

#for z in ('Nakrit','Aree','36390',13,'0642108180'):
#    print(z)

value = {'firstname':'Nakrit','lastname':'Aree','id':'36390','age':13,'tel':'0642108180'}
for key in value:
    print(value['firstname'])

Nakrit
Nakrit
Nakrit
Nakrit
Nakrit